"""
Settings - Cấu hình toàn bộ game DinoRacer
"""

# Màn hình
SCREEN_WIDTH = 1100
SCREEN_HEIGHT = 500
FPS = 60

# Màu sắc
BG_COLOR = (247, 247, 247)
GROUND_COLOR = (83, 83, 83)
TEXT_COLOR = (83, 83, 83)
DINO_COLOR = (83, 83, 83)
CACTUS_COLOR = (0, 128, 0)
BIRD_COLOR = (100, 100, 200)

# Mặt đất
GROUND_Y = 380

# Dino
DINO_X = 80
DINO_WIDTH = 70
DINO_HEIGHT = 70
GRAVITY = 1.2
JUMP_VELOCITY = -22
DUCK_HEIGHT_RATIO = 0.55

# Chướng ngại vật - Cactus
CACTUS_WIDTH = 40
CACTUS_HEIGHT_SMALL = 50
CACTUS_HEIGHT_LARGE = 80

# Chướng ngại vật - Bird
BIRD_WIDTH = 60
BIRD_HEIGHT = 40

# Tốc độ chướng ngại vật
OBSTACLE_SPEED_MIN = 6
OBSTACLE_SPEED_MAX = 18

# Khoảng cách spawn tối thiểu
MIN_OBSTACLE_SPAWN_DISTANCE = 300

# Điểm số
INITIAL_SCORE = 0
SPEED_INCREASE_INTERVAL = 10
SPEED_INCREASE_AMOUNT = 0.5

# File lưu trữ
HIGHSCORE_FILE = "highscore.json"
BEST_GENOME_FILE = "best_genome.pkl"
